a=int(input("안녕하세요. 이곳은 첫 번째 숫자를 입력하는 공간입니다."))
b=int(input("안녕하세요. 이곳은 두 번째 숫자를 입력하는 공간입니다."))
result = a + b
print(a, "+",b,"=",result)
result = a - b
print(a, "-",b,"=",result)
result = a * b
print(a, "*",b,"=",result)
result = a / b
print(a, "/",b,"=",result)
